### ISSUE TITLE
unexpected behaviour when setting up y

### ISSUE THREAD

**Issue by matipos2** [py-pdf/fpdf2#1006]
Hi

I want to setup position for y without changing position for x. So, I'm using `pdf.set_y()`. But this function will change also my x position. It's not what I expect.

Look at the source code in `fpdf.py`:
```python
    def set_y(self, y):
        """
        Moves the current abscissa back to the left margin and sets the ordinate.
        If the value provided is negative, it is relative to the bottom of the page.

        Args:
            y (float): the new current ordinate
        """
        self.x = self.l_margin
        self.y = y if y >= 0 else self.h + y
```

In my opinion this line should be removed:
```python
self.x = self.l_margin
```

**Minimal code to reproduce the problem**
```python
print(f"x={self.get_x()}, y={self.get_y()}")
self.set_x(15)
print(f"after setting x; x={self.get_x()}, y={self.get_y()}")
self.set_y(99)
print(f"after setting y; x={self.get_x()}, y={self.get_y()}")
```
It will produce:
```
x=24.16730555555555, y=205.44444444444443
after setting x; x=15, y=205.44444444444443
after setting y; x=9.999999999999998, y=99
```

**Comment by gmischler** [comment]
Welcome to fpdf2, @matipos2 !

If you look at the API documentation for [set_y()](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.set_y), you'll find that this behaviour is by design. Yes, it may be confusing to newcomers that a method by that name also changes the current x value. But it has always done that, and it has always been documented that way. Changing it now would break a lot of existing code, so that's not going to happen.

So while this may be an annoyance to some, no, it's not a bug.
If you only want to change the y value without affecting the x value, simply modify the `FPDF.y` attribute directly.

**Comment by matipos2** [comment]
> If you only want to change the y value without affecting the x value, simply modify the `FPDF.y` attribute directly.

Or use `set_xy(get_x(), y)`
Thank you for explanation and indeed, I suspected changing that in `set_y()` could break a lot of existing code, but I had to ask.
