### ISSUE TITLE
I'm not sure if it's by design or if it's a bug but .insert_toc_placeholder creates an extra blank page

### ISSUE THREAD

**Issue by peterhoang** [py-pdf/fpdf2#1091]
Consider the following code:

```python
from fpdf import FPDF

def render_toc(pdf: FPDF, outline):
    pdf.cell(pdf.epw, pdf.font_size_pt, "test")

pdf = FPDF(orientation="P", unit="in", format="Letter")
pdf.add_page()
pdf.set_margin(0.5)
pdf.set_font("Helvetica")
pdf.insert_toc_placeholder(render_toc, pages=1)

pdf.output("output/temp.pdf")
```

Notice the extra blank page at the end.

Edit: I can't seem to get the code formatter to work here...

**Comment by Lucas-C** [comment]
Hi @peterhoang

Regarding the code formatter, you can render syntax-colored block codes in GitHub Markdown using triple backquotes: \`\`\`python
\`\`\`
I edited your original post to enable this.

Now, regarding your question, yes [FPDF.insert_toc_placeholder()](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.insert_toc_placeholder) insert some blank pages in order to insert the table-of-contents in it.
Currently `fpdf2` does not offer the option to render a table-of-contents that occupies less vertical space than a page.

Now, to better understand how `fpdf2` methods work regarding ToC-rendering, I added 3 lines to your original example:
```python
from fpdf import FPDF, TitleStyle

def render_toc(pdf: FPDF, outline):
    pdf.cell(text="render_toc() test")

pdf = FPDF(orientation="P", unit="in", format="Letter")
pdf.add_page()
pdf.set_margin(0.5)
pdf.set_font("Helvetica")
pdf.insert_toc_placeholder(render_toc, pages=1)

pdf.set_section_title_styles(level0=TitleStyle(font_style="B"))
pdf.start_section("Chapter 1")
pdf.cell(text="Some text")

pdf.output("issue_1091.pdf")
```

**Comment by peterhoang** [comment]
@Lucas-C thank you very much for the clarity!
