### ISSUE TITLE
Font MPDFAA+Arial is missing the following glyphs:

### ISSUE THREAD

**Issue by blinking-led** [py-pdf/fpdf2#1171]
Greetings!

While creating PDF file with cyrillic text my code shows me:
```
Font MPDFAA+DejaVuSansCondensed is missing the following glyphs:
```
with Arial font:
```
Font MPDFAA+Arial is missing the following glyphs:
```
code
```python
pdf = FPDF()
pdf.add_page()
pdf.add_font('DejaVu', 'B', 'DejaVuSansCondensed.ttf')
pdf.set_font('DejaVu', 'B', 14)
with pdf.table(text_align=("LEFT"), borders_layout="MINIMAL", line_height = 5) as table:
     row = table.row()
     row.cell(someData)
     pdf.output(fileName, ".pdf")
```

How can I find char, string, positon or other place where message appear. I distorbing that some data was missing.

> Windows 10
> Python 3.10
> fpdf2 2.7.8

**Comment by gmischler** [comment]
It looks like your text contains some unusual non-printing characters.
Being unusual results in them not being present in some popular fonts.
Being non-printing results in them not showing up in a recognizable form in that error message.

Maybe that error message should really output the Unicode values of the missing glyphs instead of trying to print them to the console...

**Comment by blinking-led** [comment]
I'm using data only from the web to create PDF files. My script generated more than 1300 pages with a 10pt font, and I couldn't find any missing data by hand. Is the fpdf module using some parameters or arguments to show missing glyphs?

**Comment by gmischler** [comment]
If a character actually has a visible glyph, then the warning message you received would show that.

But it obviously doesn't in your case.
There are many unicode characters that are considered [whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character).
It could well be one of those that causes your message, or possibly something even more exotic.

If you really want to know what it is, use the "unicodedata" Python library module, collect all the unicode code points present in your affected data and print out their numbers and names. You may end up with something obvious, or a small list of suspects. Trying to render each of those with fpdf2 will tell you exactly who the culprit is.

**Comment by blinking-led** [comment]
In my logs, I see
`fpdf.output WARNING Font MPDFAA+DejaVuSansCondensed is missing the following glyphs:`
I use Python module logging. How can I disable this message?

**Comment by Lucas-C** [comment]
Hi @blinking-led

We have a bit of documentation regarding logging control related to `fpdf2` and its dependencies:
https://py-pdf.github.io/fpdf2/Logging.html

But overall, logging control is a broader topic.
You may want to read the official Python documentation on the subject: https://docs.python.org/3/library/logging.html

If you want to suppress those warnings programmatically in a script, a starting point could be:
```python
logging.getLogger('fpdf.output').level = logging.ERROR   # no DEBUG/INFO/WARN logs will be produced
```

> Maybe that error message should really output the Unicode values of the missing glyphs instead of trying to print them to the console...

I think that is a great idea yes!
Having both the character printed AND its unicode value displayed seems helpful.

**Comment by Lucas-C** [comment]
> > Maybe that error message should really output the Unicode values of the missing glyphs instead of trying to print them to the console...
> 
> I think that is a great idea yes! Having both the character printed AND its unicode value displayed seems helpful.

I implemented this in this PR: https://github.com/py-pdf/fpdf2/pull/1179

**Comment by blinking-led** [comment]
@Lucas-C thank you for the advice. I am already using it. But I want to see all messages in my log, but without
`missing the following glyphs`
I generate a number of files with about 2000 pages, and I see in my log a huge number **WARNING**
Can I skip _missing glyphs_ while assembling the PDF to escape this message?

**Comment by Lucas-C** [comment]
> @Lucas-C thank you for the advice. I am already using it. But I want to see all messages in my log, but without `missing the following glyphs` I generate a number of files with about 2000 pages, and I see in my log a huge number **WARNING** Can I skip _missing glyphs_ while assembling the PDF to escape this message?

I am sorry, I think that I do not quite understand what you mean 😅

> I am already using it.

Are you refering to the log filtering mechanism I mentioned, `logging.getLogger('fpdf.output').level = logging.ERROR` ?

> I want to see all messages in my log, but without `missing the following glyphs` I generate a number of files with about 2000 pages. [...] Can I skip _missing glyphs_ while assembling the PDF to escape this message?

OK, so what I understand is that you want to suppress ***only this log line*** but preserve the other DEBUG/INFO logs from the `fpdf.output` module: is that correct?

If that's correct, you may want to look into solution like this: https://stackoverflow.com/a/879937/636849

**Comment by blinking-led** [comment]
Exactly! Thank you @Lucas-C!
