### ISSUE TITLE
Font inconsistency when manually changing pages (pdf.page)

### ISSUE THREAD

**Issue by jasonfevangsafe** [py-pdf/fpdf2#1317]
FPDF allows manually setting the page being edited like `pdf.page = 1`. This causes a problem with fonts.
When changing pages, FPDF will think it's using the current font, but it's actually going to use the last-used font on the changed-to page(I think?).
`pdf.set_font()` will skip setting the font if the new font is the same as the current font. So to force fpdf to set the font fully, we can set the font to something we know won't be used prior to changing pages.

**Error details**
The output text "small" should be font size 12, but it's drawn with font size 28.

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF
pdf = FPDF()
pdf.add_page()
pdf.set_font('helvetica', size=28)
pdf.add_page()
pdf.set_font('helvetica', size=12)
# FIX: Must set font to something different to the first font used after going back to page 1
# pdf.set_font('helvetica', size=999)
pdf.page = 1
pdf.set_font('helvetica', size=12) 
pdf.cell(text="Small") # ERROR: This isn't drawn at size 12
pdf.output("hello_world.pdf")
...
```

**Environment**
Please provide the following information:
* **Operating System**: Windows
* **Python version**: Python 3.12.2
* **`fpdf2` version used**: 2.8.1

**Comment by Lucas-C** [comment]
Hi @jasonfevangsafe

Thank you for the report.

I'm not sure that we can/should fix this.

The ability to go back to a previous page is handy, but I suspect that it can cause several similar problems.
This is due to the fact that many checks/operations are performed by `.add_page()` when incrementing the page number:
* set the font (name, style & size)
* set the line width, character spacing, font stretching
* set the drawing / fill / text color
* set the line width & dash pattern
* set the page dimensions (we recently fixed a related bug: https://github.com/py-pdf/fpdf2/issues/1312) & background color or image

When one chooses to go back to a previous page, that creates a schism between the `FPDF` instance state regarding those settings, and the actual effective settings previously set in the page content stream (`self.pages[self.page].contents`).

**Comment by jasonfevangsafe** [comment]
Thanks for the detailed response! You're right it seems tricky. I don't think a change that extensive is needed, I didn't realize modifying `page.pdf` is an unreliable operation. I'm curious why ToC can "get away" with modifying `pdf.page`.

Why is it safe for ToC to modify `pdf.page`, but in my case it's not? How can I determine if I am modifying `pdf.page` in a safe manner?
Should there be a comment on `pdf.page` explaining that modifying this variable can lead to unexpected behaviour?

**Comment by Lucas-C** [comment]
> Should there be a comment on `pdf.page` explaining that modifying this variable can lead to unexpected behaviour?

Yes, that's definitely a good idea. 

> Why is it safe for ToC to modify `pdf.page`, but in my case it's not? How can I determine if I am modifying `pdf.page` in a safe manner?

We take some precautions regarding this in [FPDF._insert_table_of_content()](https://github.com/py-pdf/fpdf2/blob/master/fpdf/fpdf.py#L4806), but I suspect that a similar warning would still be welcome.

Would you like to submit a PR to improve our documentation regarding this @jasonfevangsafe 🙂 ?
Slight additions about this could be added to the docstrings, and potentially to `docs/DocumentOutlineAndTableOfContents.md`.

Else I'll perform those documentation improvements myself.
