### ISSUE TITLE
New feature: draw arcs & solid arcs

### ISSUE THREAD

**Issue by Lucas-C** [py-pdf/fpdf2#258]
One or two new methods could be added to `FPDF`,
similarly to the existing, [rect()](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.rect), [circle()](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.circle), or [ellipse()](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.ellipse)

Inspiration could be taken from [HexaPDF](https://hexapdf.gettalong.org/examples/arcs.html)

**Comment by gettalong** [comment]
@Lucas-C Nice that you draw inspiration from HexaPDF :grin:

I just saw the example output at https://pyfpdf.github.io/fpdf2/Shapes.html and wanted to note that the lines joining at the center of the green solid arc are not joined correctly. You can see artifacts sticking out:
![image](https://user-images.githubusercontent.com/4104/184820697-daee7039-aae0-4326-b98d-2d35f6fcae2e.png)

HexaPDF renders this arc like this:

![image](https://user-images.githubusercontent.com/4104/184820850-f9992f12-8c4a-47b2-a0a2-b7833de70252.png)

So you might wanna draw the whole solid arc with one continuous path instead of multiple.

**Comment by Lucas-C** [comment]
Thank you @gettalong!

At first, I thought that in order to fix this we would need to implement PDF _Line Join Styles_,
but in fact I think we should use the `h` path operator intead of cloing arcs with a line:
https://github.com/PyFPDF/fpdf2/blob/2.5.5/fpdf/fpdf.py#L1651

We should open a dedicated "bug" issue explaining the problem and how to solve it in `arc()` in `solid_arc()` methods

**Comment by gettalong** [comment]
Yeah, that could also be the reason and would certainly be easier.

**Comment by Lucas-C** [comment]
I opened #488
