### ISSUE TITLE
Adding a HTML snippet with title shows title on the beginning of PDF

### ISSUE THREAD

**Issue by ssavi-ict** [py-pdf/fpdf2#775]
**Error details**
- In `fpdf.write_html()` if we add `<title>Something</title>` in the inner `html` snippet the `title` shows at the starting line of the HTML content when rendered as a PDF.

**Minimal code**

```python
from fpdf import FPDF

TABLE_DATA = (
    ("First name", "Last name", "Age", "City"),
    ("Jules", "Smith", "34", "San Juan"),
)

pdf = FPDF()
pdf.set_font_size(16)
pdf.add_page()
pdf.write_html(
    f"""
    <!DOCTYPE html>
<html>
    <head>
        <title>New HTML</title>
    </head>
    <body>
        <table border="1">
            <thead>
                <tr>
                    <th width="25%">{TABLE_DATA[0][0]}</th>
                    <th width="25%">{TABLE_DATA[0][1]}</th>
                    <th width="15%">{TABLE_DATA[0][2]}</th>
                    <th width="35%">{TABLE_DATA[0][3]}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{'</td><td>'.join(TABLE_DATA[1])}</td>
                </tr>
                <tr>
                    <td>{'</td><td>'.join(TABLE_DATA[2])}</td>
                </tr>
                <tr>
                    <td>{'</td><td>'.join(TABLE_DATA[3])}</td>
                </tr>
                <tr>
                    <td>{'</td><td>'.join(TABLE_DATA[4])}</td>
                </tr>
            </tbody>
        </table>
    </body>
</html>""",
    table_line_separators=True,
)
pdf.output('table_html.pdf')
```
This shows following output pdf : [table_html.pdf](https://github.com/PyFPDF/fpdf2/files/11284312/table_html.pdf). The title `New HTML` is showing at the beginning of the Table.

**Suggestion**: Since this is a PDF rendering not a web-content rendering on a browser, the title should skip or it should show in such a place where it will look like a `title`.

**Environment**
Please provide the following information:
* **Operating System**: Windows 10...
* **Python version**: 3.11.1
* **`fpdf2` version used**:2.7.3

**Comment by Lucas-C** [comment]
Hi @ssavi-ict!

> the title should skip or it should show in such a place where it will look like a title

This is an interesting suggestion.
I think it would make sense if the content of a `<title>` tag does not appear on the document,
and ends up being passed to `FPDF.set_title()`.

Would you like to work on a PR?

I have a few questions:
* what if there are several `<title>` tags? (how does that behave on a web page?)
* should this logic applies only to `<title>` tags inside `<head>` tags?

**Comment by ssavi-ict** [comment]
> I think it would make sense if the content of a <title> tag does not appear on the document,

**Comment by ssavi-ict** [comment]
> I think it would make sense if the content of a <title> tag does not appear on the document, -

I also think the same. 

> ends up being passed to FPDF.set_title().

I did not catch it accordingly. Could you explain a bit more?

> Would you like to work on a PR?

Well, I am trying to explore the Codebase specifically `write_html()` method. Could you give me some resources from where I can get help? I have seen `fpdf` using python's standard `html parser` to make pdf. Did we use any `html validator` inside?


> - what if there are several <title> tags? (how does that behave on a web page?)

According to W3C, [There may only be one title in any document.](https://www.w3.org/Provider/Style/TITLE.html#:~:text=There%20may%20only%20be%20one%20title%20in%20any%20document.)

> - should this logic applies only to <title> tags inside <head> tags?

According to W3C, [The TITLE element should occur in the HEAD of the document.](https://www.w3.org/Provider/Style/TITLE.html#:~:text=The%20TITLE%20element%20should%20occur%20in%20the%20HEAD%20of%20the%20document.)

**Comment by Lucas-C** [comment]
> > ends up being passed to FPDF.set_title().
> 
> I did not catch it accordingly. Could you explain a bit more?

We could retrieve the content of the `<title>` tag and use it to define the PDF document title, using this method of `fpdf2`:
https://github.com/PyFPDF/fpdf2/blob/2.7.3/fpdf/fpdf.py#L642

> > what if there are several <title> tags? (how does that behave on a web page?)
> 
> According to W3C, [There may only be one title in any document.](https://www.w3.org/Provider/Style/TITLE.html#:~:text=There%20may%20only%20be%20one%20title%20in%20any%20document.)

Agreed, this should not happen based on the HML specification 😊
But we should should still decide how `fpdf2` will behave when parsing this HTML string:
```html
<head>
  <title>Hello</title>
  <title>World</title>
</head>
```
It's an edge case and there is no need to bother to much with it.
I suggest to avoid raising an exception, and simply call `FPDF.set_title()` each time that the HTML parser meets a `<title>` tag.

> > should this logic applies only to <title> tags inside tags?
> 
> According to W3C, [The TITLE element should occur in the HEAD of the document.](https://www.w3.org/Provider/Style/TITLE.html#:~:text=The%20TITLE%20element%20should%20occur%20in%20the%20HEAD%20of%20the%20document.)

Alright, so should we ignore `<title>` tags outside `<head>` blocks?
I think we should test how web browsers handle this, but I bet they don't ignore `<title>` even if they are misplaced.

This is all about [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle): "be conservative in what you send, be liberal in what you accept"

> Could you give me some resources from where I can get help? I have seen fpdf using python's standard html parser to make pdf. Did we use any html validator inside?

The best is to start reading the code of the `HTML2FPDF` class in `html.py` 😊
As it is a subclass of `HTMLParser`, it defines dedicated method for handling start tags (`handle_starttag`), end tags (`handle_endtag`) and tags content (`handle_data`).
You can experiment to implement the following strategy:
1. Defines a new boolean attribute `HTML2FPDF.in_title` that you set to `True` in `handle_starttag` when the tag is `title`, and then back to False in `handle_endtag`
2. In `handle_data`, if `self.in_title` is `True`, call `self.pdf.set_title()` with the string provided

**Comment by ssavi-ict** [comment]
> We could retrieve the content of the `<title>` tag and use it to define the PDF document title, using this method of fpdf2:

I am not pretty sure what `FPDF.set_title()` does right now. I tried to add it to the existing code. I did not find any such noticeable differences. 

> But we should still decide how `fpdf2` will behave when parsing this HTML string:
> Alright, so should we ignore <title> tags outside <head> blocks?
I think we should test how web browsers handle this, but I bet they don't ignore <title> even if they are misplaced.

I tried with an example earlier before posting the previous comment. That time I have seen the first `title` tag reflected. The others are skipped by the Browser. No matter where they are placed. They behave similarly even after they are placed inside the `body`. I think we can just skip processing the `title` tag.

> I suggest to avoid raising an exception, and simply call `FPDF.set_title()` each time that the HTML parser meets a <title> tag.

Agreed.

**Comment by Lucas-C** [comment]
> I am not pretty sure what `FPDF.set_title()` does right now. I tried to add it to the existing code. I did not find any such noticeable differences.

It sets the document title, which is not visible **inside** the document,
but usually displayed by the PDF viewer in its top window title bar.

**Comment by ssavi-ict** [comment]
>It sets the document title, which is not visible inside the document,
but usually displayed by the PDF viewer in its top window title bar.

Ahh.. I got that now. However, it behaves differently based on the PDF reader. I tried to open generated PDF in Mozilla, Chrome, and Foxit Reader (the PDF reader I use). The result is following -

- Mozilla ( _Shows Both filename and set title_ )
![mozila](https://user-images.githubusercontent.com/14172268/233755806-bd1f5171-c9ae-47b7-9792-9c30fc419d0c.PNG)
- Chrome ( _Shows only the set title_ )
![chrome](https://user-images.githubusercontent.com/14172268/233755804-1440118c-cc90-45b9-8b46-d49e265030a7.PNG)
- Foxit Reader ( _Shows only the filename_ )
![foxit_example](https://user-images.githubusercontent.com/14172268/233755805-8319157d-10e3-4f88-a072-f6b8bf8f2d68.PNG)

**Comment by Lucas-C** [comment]
Yeah, that doesn't really surprise me...

Maybe we could improve our documentation to describe more what this method does,
and the fact that PDF viewers will not all display it?
https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.set_title

**Comment by Lucas-C** [comment]
> On the other hand, a user can easily insert several HTML documents in a single PDF, each of which may have its own `<title>` tag. How are we going to handle this situation?

We discussed that in previous comments above 😅

In a similar way that PDF documents are independents, HTML are also very independents from each other.
There is no concept of "sheets", like in Microsoft Excel, in neither of those formats.

PDF documents can be merged, so that 2 documents are appended one after the other in a file,
and that can be useful for printing.
But then the final document title does not have much sense,
and I don't know of any software that has a notion of "several documents in a single PDF file".

For all those reasons, it seems better to be to not bother to much about this case,
and implement the basic rule that we suggested: _avoid raising an exception, and simply call FPDF.set_title() each time that the HTML parser meets a <title> tag_.

> Maybe we should make the meta data transfer optional? Possibly including an option of having it appear on page anyway?

I am not sure this is a good idea.
In order for `fpdf2` to be best predictable for our users, we should follow closely the behaviour of web browsers regarding how HTML tags are handled.
A `<title>` is **never** displayed on the page and **always** displayed in the status bar of a browser window / tab.
So I think that is what `fpdf2` should do by default: **never** display the `<title>` tags content on the page, and **alway** use it as metadata to set the PDF document title.

If users want a visible big top header text at the beginning of their document, they can use a `<h1>`, which is designed for that purpose in the HTML syntax.

And regarding making this behaviour optional / configurable, it wouldn't be ideal to implement with HTML attributes (as this is a non-standard feature), and I don't see any good reason to have this degree of fine control...
End users will still be able to call `FPDF.set_title("")` if they want to remove a title inserted from HTML passed to `write_html()`

**Comment by gmischler** [comment]
> We discussed that in a previous comments above 😅

Yes, but I don't see a real conclusion.

> In order for `fpdf2` to be best predictable for our users, we should follow closely the behaviour of web browsers regarding how HTML tags are handled.

As a default, that seem reasonable (as far as possible).

Within a single HTML document, that is fairly easy:
* Ignore `<title>` tags outside of `<head>` (even if browsers will try to process invalid HTML, in this case I think we shouldn't)
* Witin `<head>`, place the first `<title>` in the PDF meta title, and ignore all others after that.

If we process several HTML files, it gets a bit trickier.
Your suggestion seems to be to just call `FPDF.set_title()` each time we encounter a valid HTML `<title>`. This would mean that the `<title>` of the **_last_** imported HTML file overwrites all previous ones. As a user, this is not really what I'd expect to happen.

Maybe we should set the PDF title to a HTML `<title>`  **_only_** if the `pdf.title` attribute is still empty? That way a document title previously set by the user won't be overwritten. And when importing several HTML files, the `<title>` of the first one persists. This behaviour would make the most sense to me, and extends the concept behind the HTML specs (use the first seen) to a multi-document situation.

Independently of and in addition to the above, we should keep the option available to deliberately make the `<title>` show up on the page. This could be useful if a user imports several HTML snippets, and wants the source of each one to be shown, maybe with a suitable `H#` styling. Obviously, such an option would have to be off by default.
Fpdf2 has shown the title on the page for many years. Eliminating this possibility completely might cause difficulties for some existing users.

**Comment by Lucas-C** [comment]
> Maybe we should set the PDF title to a HTML `<title>` **_only_** if the `pdf.title` attribute is still empty? That way a document title previously set by the user won't be overwritten. And when importing several HTML files, the `<title>` of the first one persists. This behaviour would make the most sense to me, and extends the concept behind the HTML specs (use the first seen) to a multi-document situation.

Agreed, this also makes sense to me and seems like a good idea!

> fpdf2 has shown the title on the page for many years. Eliminating this possibility completely might cause difficulties for some existing users.

That is a good point.
Alright, let's add a new optional `display_title_tag` or `render_title_tag` parameter to [HTML2FPDF](https://pyfpdf.github.io/fpdf2/fpdf/html.html#fpdf.html.HTML2FPDF) then, with a default value to `False`, and clearly document this change in `CHANGELOG.md`

**Comment by Lucas-C** [comment]
@ssavi-ict are you considering writing a PR implementing this? 😊

Do you have questions regarding what we discussed? Is it all clear for you?

**Comment by ssavi-ict** [comment]
@Lucas-C, yes it is clear so far. 
I am reading the Codebase basically how `HTML` contents are parsed into `fpdf2` and how the contents are rendered into the output pdf. Once I get this, I will surely implement this. I am reading the `HTML2FPDF` class. 

Will that be enough? Do I need more things to explore? 

I will try to find something out by the weekend. Actually a bit busy with office assignments nowadays and also the implementations are also taking to understand.

**Comment by Lucas-C** [comment]
> Will that be enough? Do I need more things to explore?

I think that should be enough. The unit tests may also be helpful: https://github.com/PyFPDF/fpdf2/blob/master/test/html/test_html.py
But if you have any questions, please ask away! 😊

> Actually a bit busy with office assignments nowadays and also the implementations are also taking to understand.

No worries and no hurry, take your time 👍

**Comment by Lucas-C** [comment]
Hi @ssavi-ict!

Have you been able to work towards this?

If not, no worries 😊
I'd just like to know if we should invite other contributors to work on this issue.

**Comment by 0x00zer0day** [comment]
I am a newbie and would like to work on this issue, could you please guide me a little through the process?

**Comment by Lucas-C** [comment]
Hi @0x00zer0day and welcome!

Sure, I will try to guide through the process 🙂

1. First, setup a development environment by forking this GitHub repository, cloning your fork, and follow the instructions in our documentation page dedicated to `fpdf2` development: <https://py-pdf.github.io/fpdf2/Development.html> (especially the "Installing fpdf2 from a local git repository" & "Testing" sections). If you work under Windows, I would also recommend to instal Sumatra PDF reader, a great PDF document viewer that can hot-reload PDF files when they are modified.

2. Start by adding unit tests, in `test/html/test_html.py`, taking inspiration from existing tests.
The goal is to write the minimal code possible that covers the feature you are implementing.
Initially, you will need to pass `generate=True` to `assert_pdf_equal()` in order for a reference PDF file to be generated.

3. Then, modify the code in `fpdf/html.py` in order to implement the feature.

4. Finally, when your tests are passing and you are happy with your code, create a Pull Request in order to get a code review from maintainers. Also please a mention of this bahaviour in `docs/HTML.md`

For this specific issue, the goal is to:

* add support for `<title>` HTML tag in `HTML2FPDF.handle_starttag()`.
The logic should be: if `getattr(self.pdf, "title", None)` is `None`, then set it, else do nothing.

* add a new `render_title_tag=False` parameter to `HTML2FPDF.__init__`, and store it as `._render_title_tag`.
When this is `True`, then a `<title>` HTML tag should be rendered as a _heading_ (like `h1`, `h2`...).

Do you have any question about those instructions? 😊

**Comment by yashj09** [comment]
i am a newbie and i am not able to find this issue in the repo can you please help me

**Comment by Lucas-C** [comment]
Hi @yashj09

What do you mean by "i am not able to find this issue in the repo" ?

**Comment by Lucas-C** [comment]
Hi @yashj09 & @sankarebarri?

Is one of you actively working on this? Do you need help?
Or else, can other `fpdf2` contributors work on this?

**Comment by yashj09** [comment]
@Lucas-C  sorry , i am not working on it

**Comment by sankarebarri** [comment]
Hi @Lucas-C , i am actively working on it.
I have already created a test which is failing. I am inspecting the code `fpdf/html.py.HTML2FPDF`. It's taking me time to figure out what is what. I should be able to finally fix it before next Monday. If not, then you can assign it to someone else.

Thanks.

**Comment by Lucas-C** [comment]
> I have already created a test which is failing. I am inspecting the code `fpdf/html.py.HTML2FPDF`. It's taking me time to figure out what is what. I should be able to finally fix it before next Monday. If not, then you can assign it to someone else.

Excellent!
Sure, no hurry, it's totally OK to take your time.
You can rely on our (the maintainers) help if you need! 😊

**Comment by sankarebarri** [comment]
> > I have already created a test which is failing. I am inspecting the code `fpdf/html.py.HTML2FPDF`. It's taking me time to figure out what is what. I should be able to finally fix it before next Monday. If not, then you can assign it to someone else.
> 
> Excellent! Sure, no hurry, it's totally OK to take your time. You can rely on our (the maintainers) help if you need! 😊

Hello @Lucas-C, i hope i am not doing this wrong. Help from anyone would be highly appreciated.
I have 2 cases:
Case 1:
1. In `/tmp/pytest-of-runner/pytest-0/test_html_simple_table0`, i can only see **actual.pdf** but not
**actual_qpdf.pdf and 
expected_qpdf.pdf**
contrary to [the documentation ](https://py-pdf.github.io/fpdf2/Development.html)

2. So, i tried to do go around it. I initially did `assert_pdf_equal(pdf, HERE / "html_render_title.pdf", tmp_path, generate=True)`
![generate=True](https://github.com/py-pdf/fpdf2/assets/96892550/47ccd35f-edc5-4f32-85db-8eddaa57f6e9)
which created `html_render_title.pdf` in `test/html`, with **no title in the html** because i consider this pdf to be the one to be matched, i.e the expected pdf.
So i am now running the test against the actual.pdf being generated everytime i run` pytest -k test_render_title`
![generate=False](https://github.com/py-pdf/fpdf2/assets/96892550/35a1f0d0-478a-4c01-8bfb-b178b6815a41)
but with **title in the html** and generate=True not being called,.

Is that the correct way to compare the expected pdf and the actual pdf? or is there a better way?

**Comment by sankarebarri** [comment]
> > > I have already created a test which is failing. I am inspecting the code `fpdf/html.py.HTML2FPDF`. It's taking me time to figure out what is what. I should be able to finally fix it before next Monday. If not, then you can assign it to someone else.
> > 
> > 
> > Excellent! Sure, no hurry, it's totally OK to take your time. You can rely on our (the maintainers) help if you need! 😊
> 
> Hello @Lucas-C, i hope i am not doing this wrong. Help from anyone would be highly appreciated. I have 2 cases: Case 1:
> 
>     1. In `/tmp/pytest-of-runner/pytest-0/test_html_simple_table0`, i can only see **actual.pdf** but not
>        **actual_qpdf.pdf and
>        expected_qpdf.pdf**
>        contrary to [the documentation ](https://py-pdf.github.io/fpdf2/Development.html)
> 
>     2. So, i tried to do go around it. I initially did `assert_pdf_equal(pdf, HERE / "html_render_title.pdf", tmp_path, generate=True)`
>        ![generate=True](https://user-images.githubusercontent.com/96892550/281573924-47ccd35f-edc5-4f32-85db-8eddaa57f6e9.png)
>        which created `html_render_title.pdf` in `test/html`, with **no title in the html** because i consider this pdf to be the one to be matched, i.e the expected pdf.
>        So i am now running the test against the actual.pdf being generated everytime i run` pytest -k test_render_title`
>        ![generate=False](https://user-images.githubusercontent.com/96892550/281574244-35a1f0d0-478a-4c01-8bfb-b178b6815a41.png)
>        but with **title in the html** and generate=True not being called,.
> 
> 
> Is that the correct way to compare the expected pdf and the actual pdf? or is there a better way?

Case 2:
I have add support for `<title> HTML tag in HTML2FPDF.handle_starttag().`:
![render_title](https://github.com/py-pdf/fpdf2/assets/96892550/08d39282-1e80-49aa-a0b4-b07a4f191128)
and set it too:
![set_render](https://github.com/py-pdf/fpdf2/assets/96892550/f6acd006-7d15-43e8-80ba-b1f04b43bd85)

In `handle_starttag`, i have done
![title=True](https://github.com/py-pdf/fpdf2/assets/96892550/be232dbc-af1d-4592-9ea3-ac48f757fc63)

and in `handle_data` i have done:
![handle_data](https://github.com/py-pdf/fpdf2/assets/96892550/6befae95-2f83-435b-b440-f138c530142a)

I thought `handle_data `should be extracting the contents between the html tags and convert them to the expected pdf, but  i can't seem to get my head around it.

This is my first time trying to contribute to a code of high caliber like this, please bear with me while you walk me through.I am actually getting familiarised with the the codes and  I am seeing myself being a long time contributor to this repository, if i finally know my way around.

Thanks.

**Comment by gmischler** [comment]
> This is my first time trying to contribute to a code of high caliber like this, please bear with me while you walk me through.I am actually getting familiarised with the the codes and I am seeing myself being a long time contributor to this repository, if i finally know my way around.

It helps to understand that the HTML parser is essentially a state machine (even if not a very sophisticated one).

Every time it encounters a start tag, it changes its internal state accordingly, and when it encounters the matching end tag it resets back to the previous state (you're not currently doing that). And while in any specific state, `handle_data()` needs to adapt its behaviour, and put the text it receives into the appropriate bucket.

In your case, first I don't understand why you want to make `render_title_tag` a constructor argument. There's no good reason to make this functionality configurable, so just establishing a private attribute is enough. You may also want to give it a different name, since rendering the title is explicitly _not_ what should happen. You could initialize it eg. with `self._in_title = False`

While in title parsing state, you just want to collect all the text that comes in (could theoretically be in several consecutive calls). So all that `handle_data()` needs to do is collect its data. Therefore you need another private attribute with an (originally empty) list as ist value, where `handle_data()` appends its data, say eg. `self._title_data = []`.

Only when the title tag gets closed (in `handle_endtag()`) can you finally process the collected data. Strangely, `FPDF.title` does not get initialized by default (you could change that). In any case, if it either doesn't exist or is None, then now you want to concatenate the collected strings, maybe clean up the result with `_WS_SUB_PAT.sub(" ", data)`, and hand it over to `FPDF.set_title()`. If `FPDF.title` already has a value, you shouldn't touch it and throw the collected data away. And as the last thing you need to clear the title parsing flag and empty the title data list again.

It's not really all that complicated, once you have grasped the basic concept.

**Comment by Lucas-C** [comment]
Hi!

Just wondering if there are still people working on this? 🙂
Else I guess this is `up-for-grabs`.

**Comment by YuvalBubnovsky** [comment]
@Lucas-C 

Hi!
As I would like to get into contributing to py-pdf I notices this issue is both `up-for-grabs` and `good first issue`.

I've gone and read through your entire discussion on the matter, so far everything seems clear (hopefully no surprises during implementation)

Mind assigning this to me? Will get to working on this over the weekend.

**Comment by YuvalBubnovsky** [comment]
> @Lucas-C
> 
> Hi! As I would like to get into contributing to fpdf2, I noticed this issue is both `up-for-grabs` and `good first issue`.
> 
> I've gone and read through your entire discussion on the matter, so far everything seems clear (hopefully no surprises during implementation)
> 
> Mind assigning this to me? Will get to working on this over the weekend.

Just updating that I'm still on this, but as I'm job searching right now - I have a big interview coming up on Tuesday so I'll focus on that first.

This is still in progress by me.

**Comment by Lucas-C** [comment]
Good luck with your job interview @YuvalBubnovsky 🤞

And thank you for your work on, this 👍

**Comment by YuvalBubnovsky** [comment]
Sorry, un-assigning myself from this

**Comment by Lucas-C** [comment]
Alright, it's fine 🙂

This issue is up-for-grabs then!

**Comment by Lucas-C** [comment]
I opened PR https://github.com/py-pdf/fpdf2/pull/1298 to implement this
