### ISSUE TITLE
svg exported from matplotlib not inserted correctly - add support for clip-path & clipPath

### ISSUE THREAD

**Issue by RubendeBruin** [py-pdf/fpdf2#858]
Describe the bug

**Error details**

Matplotlib plots where the plot contents exceed the figure range are included wrongly in the pdf when exported to svg.

Expected:
(this is the .svg file exported from matplotlib)
![matplotlib](https://github.com/PyFPDF/fpdf2/assets/34062862/9a29c1b1-5bf3-4cb3-8eae-68d9057c2506)

Result:
![image](https://github.com/PyFPDF/fpdf2/assets/34062862/6a77ed32-d9e3-4a09-b522-df4987971719)

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.image("matplotlib.svg")
pdf.output("matplotlib.pdf")
```
![matplotlib.pdf](https://github.com/PyFPDF/fpdf2/files/12123381/matplotlib.pdf)

**Environment**

Please provide the following information:
OS: Windows 10
Python 3.11
matplotlib: matplotlib-3.7.2
fpdf2: latest master branch

**Comment by gmischler** [comment]
Hi @RubendeBruin, thanks for reporting this!

The documention doesn't mention it, but looking at the code it seems that our SVG parser doesn't currently support clipping.

In your example, there is a clipping rectangle defined for each of the two graphs, so that matplotlib doesn't need to verify if anything it draws is actually visible. Consequently, we draw the part of one curve that doesn't fit inside of the graph area all over the place.

Fortunately, our drawing.py module actually does support clipping. Therefore it should not be too hard to add this feature to the SVG parser as well, if anyone is motivated enough to do so... :wink:

**Comment by Lucas-C** [comment]
I fully agree with @gmischler analysis

Moreover, it would be nice to have a minimal SVG file that reproduce the issue...
I don't think you provided the SVG file @RubendeBruin, and it's not really a minimal example 😅

**Comment by RubendeBruin** [comment]
Here is the minimal example:

make the .svg
```
import matplotlib.pyplot as plt

fig, plt = plt.subplots()
plt.plot([0,2])
plt.plot([0,1],[1,1])
plt.set_ylim(0,1)
plt.axis('off')
fig.savefig(r'minimal.svg')
```
produces:

![minimal](https://github.com/PyFPDF/fpdf2/assets/34062862/5adf6d3d-796a-416e-baef-20584c5a24f1)


make the PDF:
```
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.image(r'minimal.svg', w=100)
pdf.output(r'minimal.pdf')
```

**Comment by Lucas-C** [comment]
That's perfect, thank you @RubendeBruin!

**Comment by afriedman412** [comment]
hi -- is anyone working on this? I'd like to if not!

**Comment by Lucas-C** [comment]
> hi -- is anyone working on this? I'd like to if not!

I don't think anyone is currently working on this, you are welcome to do so!

**Comment by afriedman412** [comment]
let me know if I'm wrong, but I don't think the SVG import currently supports `id` references from `defs`

I tried to convert this ...
```
<?xml version="1.0" encoding="utf-8"?>
<svg viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg" version="1.1">
  <path d="M 50 40 L 400 40" style="stroke: red"/>
  <use href="#rrr" x="50" y="50"/>

  <defs>
    <g id="rrr">
      <rect width="20" height="20" fill="lime" />
    </g>
  </defs>
</svg>
```

like this ...
```
pdf = fpdf.FPDF()
pdf.add_page()
pdf.image("./clipping-tests/def_rect.svg")
pdf.output("def_rect.pdf")
```

and got a ValueError

I'm going to build out `defs` regardless but let me know if I'm missing something here.

**Comment by gmischler** [comment]
> I'm going to build out defs regardless but let me know if I'm missing something here.

If you look at the method [`build_xref()`](https://github.com/py-pdf/fpdf2/blob/ab228614dd7220f6e562b0858adc41abc51e5d34/fpdf/svg.py#L867C32-L867C32) where this error happens, you'll find a comment by the author:

    # this assumes xrefs only reference already-defined ids.
    # I don't know if this is required by the SVG spec.

You'll probably have to fix that, so that any referenced IDs are only required to exist during the rendering phase.

**Comment by Lucas-C** [comment]
> thanks -- the first problem was that fpd2 reads tags in order, so if the `defs` are at the end of the file, it won't know the ID's. I fixed that.

Great, good job! 👍

> also -- I had to install a few other things (Ghostscript, Java, SWIG) to get the testing to work, so I'm adding that to the Development tutorial page!

I'm really surprised that you had to install all those things...
Why did you need Ghostscript / Java / SWIG exactly?

**Comment by afriedman412** [comment]
ok the good news:
- SVG clipping paths work
- shapes can now be defined in the `defs` tag for later cross-referencing
- SVG cross-referencing code streamlined a tiny bit

the bad news:
- I can't get any of my SVG's to pass the hashing test (even if I just duplicate one that's already in the test SVG folder)?

I'm using the exact same code that the test function does to convert to pdf...
```
svg = fpdf.svg.SVGObject.from_file(path/to/svg)
pdf = fpdf.FPDF(unit="pt", format=(svg.width, svg.height))
pdf.add_page()
svg.draw_to_page(pdf)
pdf.output(path/to.pdf)
```

- I think there are some conversion issues with the `stroke` param

> I'm really surprised that you had to install all those things... Why did you need Ghostscript / Java / SWIG exactly?

make red number green? Some Camelot tests were failing because I didn't have those libraries.

anyways -- you got any ideas about the testing issue?

**Comment by afriedman412** [comment]
> anyways -- you got any ideas about the testing issue?

nm figured it out, it's the metadata (creation date and ID)

what's best practices for getting around that?

**Comment by andersonhc** [comment]
> > anyways -- you got any ideas about the testing issue?
> 
> nm figured it out, it's the metadata (creation date and ID)
> 
> what's best practices for getting around that?

We write our tests using [assert_pdf_equal()](https://github.com/py-pdf/fpdf2/blob/aa3b1f4a1e16b1d513e5064278b2fb2f5b2747af/test/conftest.py#L55) instead of output()

asset_pdf_equal() sets the creation timestamp to a fixed value (EPOCH) so all test results are the same.

The ID should be the same if the content (including creation date) is the same.

**Comment by Lucas-C** [comment]
> is this like common domain knowledge or should I add something to the contributing docs about this? I spent a few hours trying to figure it out....

It's documented there: https://py-pdf.github.io/fpdf2/Development.html#assert_pdf_equal-writing-new-tests

But PRs to improve our documentation are welcome! 😊

**Comment by afriedman412** [comment]
ha I think I just added that? either way, all good!

**Comment by Lucas-C** [comment]
Oh yeah, you added the section "Generating PDF files for testing" #968
Thanks 😊
