### ISSUE TITLE
How does one set the color for h1, h2 ... etc. html tags?

### ISSUE THREAD

**Issue by augb** [py-pdf/fpdf2#900]
When I generate my PDF, I have the text color set to black. I have my footer color set to another color, as well. I cannot figure out how to change the coloring on header tags (e.g. `<h1>`, `<h2>`, etc.). Currently, it is a maroon color, but I would like it to be black or some other color.

Example:
<img width="256" alt="Screenshot 2023-08-17 at 3 12 58 PM" src="https://github.com/py-pdf/fpdf2/assets/841357/bbd2a549-21c3-4c8b-9fcc-4174e2597687">

Please advise. Thanks.

**Comment by Lucas-C** [comment]
Hi @augb

What a coincidence! This problem was also reported last week in #880
I implemented a solution in #886.
You will now be able to do this: `<h2 color="#00ff00">Subtitle in green</h2>`

This feature has not been released yet, but you can use it by installing `fpdf2` directly from the `master` branch of this repo with this command:

    pip install git+https://github.com/PyFPDF/fpdf2.git@master

**Comment by augb** [comment]
@Lucas-C Thank you!
