### ISSUE TITLE
Tests in github workflow failing  [test_cell_speed_with_long_text]

### ISSUE THREAD

**Issue by RubendeBruin** [py-pdf/fpdf2#923]
The test "test_cell_speed_with_long_text" _sometimes_ fails due to a too long execution time.

The test is:

```
@ensure_exec_time_below(seconds=20)
@ensure_rss_memory_below(mib=1)
def test_cell_speed_with_long_text():  # issue #907
    pdf = FPDF()
    pdf.add_font(fname=FONTS_DIR / "DejaVuSans.ttf")
    pdf.set_font("DejaVuSans", size=5)
    pdf.add_page()
    assert len(LONG_TEXT_LINES) == 26862
    for line in LONG_TEXT_LINES:
        pdf.cell(0, 3, line, new_x="LMARGIN", new_y="NEXT")
```

and the resulting error is:

https://github.com/py-pdf/fpdf2/actions/runs/6171782769/job/16750710021?pr=797#step:10:1592https://github.com/py-pdf/fpdf2/actions/runs/6171782769/job/16750710021?pr=797#step:10:1592

<img width="525" alt="image" src="https://github.com/py-pdf/fpdf2/assets/34062862/b3fb2703-1df6-4e68-8fdd-d9482acb40ce">

Solving would be as simple as increasing the allowed execution, but that would also basically void the test.

**Comment by Lucas-C** [comment]
Yes, you are right, I have also witnessed this 🙂

I think we could bump that to 21 seconds to improve the pipeline stability
while not sacrificing too much in terms of performance control.

**Comment by Lucas-C** [comment]
I happened again:
* https://github.com/py-pdf/fpdf2/actions/runs/6331004525/job/17194652534
* https://github.com/py-pdf/fpdf2/actions/runs/6331014983/job/17194683746

But each time the execution time was above 21s, so my solution would not work...

**Comment by gmischler** [comment]
Can we please finally fix this?

I can see absolutely no value in blocking the pipeline just because something took longer than expected on some random system configuration. Rerunning all tests in the hope it might then succeed makes the problem worse, because it increases the total load on the cloud boxes hosting the virtual test systems even more.
I'm not mistaken, the "failed" tests also keep codecov from doing its job.

It would be completely sufficient to just measure the time taken and report the result.
I have no experience with the pipeline mechanics involved, or I'd do it myself...

**Comment by Lucas-C** [comment]
I slightly increased the limits: https://github.com/py-pdf/fpdf2/commit/40d64d4db32d4afd0cdb9e6e1d38cf06e6930e2f

**Comment by Lucas-C** [comment]
I believe this problem with `test_cell_speed_with_long_text()` did not happen again since I increased the limit.

Closing this for now, but feel free to reopen it, or to open another issue, if need be.
