### ISSUE TITLE
set_dash_pattern fails under certain conditions

### ISSUE THREAD

**Issue by abubelinha** [py-pdf/fpdf2#992]
**Error details**
No errors are raised but sometimes `set_dash_pattern()` does not work as I expected.
This happens -at least- when you add a page and try to set a pattern identical as the last pattern set in the previous page.

**Minimal code**

The 2nd page produces a not dashed line. Why?

```python
from fpdf import FPDF
pdf = FPDF()
pdf.set_line_width(0.5)
pdf.set_draw_color((255,0,0))

pdf.add_page() # 1st PAGE:
pdf.set_dash_pattern(dash=1, gap=3) # If you set again this pattern as the 1st one in the next page, it won't work
# you can draw a line here or not, it doesn't matter:
pdf.line(x1=10, y1=10, x2=100, y2=10) # this is a dashed line, as expected

pdf.add_page() # 2nd PAGE:
# <--- if I had set a different pattern here, then the next error would not occur.
pdf.set_dash_pattern(dash=1, gap=3) # if I repeat the last pattern set in previous page, it won't work
pdf.line(x1=10, y1=10, x2=100, y2=10) # this SHOULD BE a dashed line, but it is not !!

pdf.add_page() # 3rd PAGE:
pdf.set_dash_pattern(dash=2, gap=3) # I need to do this to avoid the next fail
pdf.set_dash_pattern(dash=1, gap=3) # now I re-set the last used pattern, and it will work:
pdf.line(x1=10, y1=10, x2=100, y2=10) # this is a dashed line, as expected

pdf.output("fpdf-dashbug-test.pdf")
```

**OUTPUT:** [fpdf-dashbug-test.pdf](https://github.com/py-pdf/fpdf2/files/13209276/fpdf-dashbug-test.pdf)

**Environment**
Please provide the following information:
* **Operating System**: Windows 7, 64 bit
* **Python version**: 3.8.7
* **`fpdf2` version used**: 2.7.6

Thanks
@abubelinha

**Comment by gmischler** [comment]
Thanks for the report, @abubelinha !

The PDF standard resets the graphics state to defaults for each new page, including the dash pattern. fpdf2 follows the opposite approach, and resets them to the previous values after a page switch... except for the dash patterns at the moment. So our internal settings and the reality in the PDF file get out of sync. Because it doesn't reset its internal value to defaults either, if you set the same pattern again, it will consider that redundant and do nothing.

We'll have to fix that...

**Comment by gmischler** [comment]
#993 fixes the problem, and will be part of release 2.7.7.
